documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'doc/**'
              - 'requirements-docs.txt'

rst:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'doc/source/**/*.rst'

config:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/**'
              - 'doc/Makefile'
              - 'doc/make.bat'
