repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: check that hooks apply
        description: check that all the hooks apply to the repository
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python imports)
        language: python
        types: [python]
        files: \.py$
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.12.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
        name: run check for not-real mock methods
        description: Prevent common mistakes of assert mck.not_called(), assert mck.called_once_with(...) and mck.assert_called
      - id: python-no-eval
        name: run check for eval()
        description: A quick check for the eval() built-in function
      - id: python-no-log-warn
        name: run check for use logger.warning(
        description: A quick check for the deprecated .warn() method of python loggers
      - id: python-use-type-annotations
        name: run check for type annotations not comments
        description: Enforce that python3.6+ type annotations are used instead of type comments
      - id: rst-backticks
        name: run rst-backticks
        description: detect common mistake of using single backticks when writing rst
      - id: rst-directive-colons
        name: run rst-directive-colons
        description: detect mistake of rst directive not ending with double colon or space before the double colon
      - id: rst-inline-touching-normal
        name: run rst-inline-touching-normal
        description: detect mistake of inline code touching normal text in rst
      - id: text-unicode-replacement-char
        name: run check for no unicode replacement char
        description: Forbid files which have a UTF-8 Unicode replacement character
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        name: run markdownlint
        description: check Markdown files with markdownlint
        args: [--config=.github/linters/.markdown-lint.yml]
        types: [markdown]
        files: \.md$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: run yamllint
        description: check YAML files with yamllint
        args: [--strict, -c=.github/linters/.yaml-lint.yml]
        types: [yaml]
        files: \.ya?ml$
